from counterparty_verification.prompt_constants import (
    EVALUATOR_INSTRUCTIONS,
    MCP_SERVER_INSTRUCTIONS,
    QUESTION_ANSWER_INSTRUCTIONS,
    REPUTATION_AGGREGATOR_INSTRUCTIONS,
    SPECIALIST_INSTRUCTIONS,
    SYSTEM_GROUNDING,
)


def test_all_prompt_constants_are_loaded() -> None:
    prompts = (
        MCP_SERVER_INSTRUCTIONS,
        SYSTEM_GROUNDING,
        SPECIALIST_INSTRUCTIONS,
        EVALUATOR_INSTRUCTIONS,
        QUESTION_ANSWER_INSTRUCTIONS,
        REPUTATION_AGGREGATOR_INSTRUCTIONS,
    )

    assert all(prompt.strip() for prompt in prompts)
    assert SYSTEM_GROUNDING in SPECIALIST_INSTRUCTIONS
    assert SYSTEM_GROUNDING in EVALUATOR_INSTRUCTIONS
    assert SYSTEM_GROUNDING in QUESTION_ANSWER_INSTRUCTIONS
    assert SYSTEM_GROUNDING in REPUTATION_AGGREGATOR_INSTRUCTIONS
